### ISSUE TITLE
[ledger] allow for editing derivation path

### ISSUE THREAD

**Issue by dylanschultzie** [aptos-labs/petra-wallet#10]
It would be nice to be able to manually edit the derivation path, or at least the account number. Currently only up to `m/44'/637'/0'/0'/0'` through `m/44'/637'/7'/0'/0'` is supported, but there's no need for that limitation. Adding either a `Next` button to see further accounts, or allowing for manually editing the account number would solve this issue.

<img width="551" alt="Screenshot 2023-03-14 at 12 55 55 PM" src="https://user-images.githubusercontent.com/9121234/225121901-7f062ad4-a4c0-481a-ba9c-7db06d83e038.png">

**Comment by hariria** [comment]
Cc @hardsetting

**Comment by hardsetting** [comment]
Agreed, let's add a manual input there.
Thanks for bringing it up @dylanschultzie

**Comment by bv-aptos** [comment]
This has been fixed with 1.2.71. Please let us know what you think! (And feel free to reopen if you still have issues)

#44 duplicates this issue.
