### ISSUE TITLE
Transaction error

### ISSUE THREAD

**Issue by alpzk** [aptos-labs/petra-wallet#29]
When I tried to claim OAT from Galxe I got this error always from Petra Wallet: 

Transaction error
{"message":"Account not found by Address(0x57...f256) and Ledger version(381038518)","error_code":"account_not_found","vm_error_code":null}

Payload
Function: 0xe7c7bb0e53fc6fb86aa7464645fbac96b96716463b4e2269c62945c135aa26fd::oat::claim

**Comment by bv-aptos** [comment]
This has been fixed a while back! So sorry for the late reply. Please have a look again! (please reopen if still an issue)
