### ISSUE TITLE
Help with the transaction

### ISSUE THREAD

**Issue by abobus228899** [aptos-labs/petra-wallet#30]
![petra](https://github.com/aptos-labs/petra-wallet/assets/155471789/20caed72-cfc0-4363-bf25-ccef0480a38f)

**Comment by bv-aptos** [comment]
There are several things that can happen that would cause the transaction to expire. I see this issue is quite old.  Closing for now, hopefully the myriad updates/fixes since Jan has resolved your issue. (Please feel free to reopen if not)
