### ISSUE TITLE
Seedz unstake error

### ISSUE THREAD

**Issue by Burakk112** [aptos-labs/petra-wallet#33]
Hello dear administrator. First of all, I'm using translation, sorry if it's wrong. I staked SEEDZ 3-4 months ago, but I cannot unstake my SEEDZ now. Please help me.
Mail: burakotay99@gmail.com
X: Burakkk987

My wallet address I got from the echo site: 0x6b2e290efe75a9a74317ee8edaf33603b29bb8e67a9b6b730317c7c819b1ead4
![photo1716284601](https://github.com/aptos-labs/petra-wallet/assets/170414280/58316419-a78f-4133-9ff4-81b9f5928be8)

**Comment by bv-aptos** [comment]
I am not sure on the functionality of the seedz site. You will have to reach out to their team directly to figure out why you cannot unstake. 

If you have any questions about your interactions with Petra Wallet specifically, happy to try to help resolve those.
