### ISSUE TITLE
Cannot use my account anymore, `INVALID_AUTH_KEY`, explorer shows `account::rotate_authentication_key`

### ISSUE THREAD

**Issue by greg7mdp** [aptos-labs/petra-wallet#35]
The explorer show that the last transaction in my account was [account::rotate_authentication_key](https://explorer.aptoslabs.com/account/0xaf65a016379fd3f8ad8b3a2bfaf3e8d106c98f81986a60dbd941a9c1dc4693b8?network=mainnet).

I have no idea how that happened. I certainly do not remember doing anything like that. 
Is that something that can be done with `Petra`?

I still have my account's private key. Is there a way for me to gain access to my account again?

**Comment by bv-aptos** [comment]
Petra wallet (extension and mobile) block calls to rotating authentication key when interacting with dapps. And we also don't offer the ability to perform that action from within either client (extension or mobile). 

Unfortunately there is no way to gain access to your account again once the keys have been rotated. 

Do you use any other wallets? Or do you have any idea how your private key/mnemonic phrase might have been compromised?

**Comment by greg7mdp** [comment]
Thanks for the answer. Honestly, I have no recollection how this happened. I don't think my keys or mnemonic have been compromised, and I don't use another Aptos wallet. I guess there is no way to know where the transaction originated from, so I may never know. Still it is good to know that it was not from Petra. Thanks!
