### ISSUE TITLE
Please, help us interact with smart contracts.

### ISSUE THREAD

**Issue by IgoresVer** [aptos-labs/petra-wallet#4]
We need parameter fields in the wallet:
smart contract address, function, type_arguments, arguments

**Comment by Helpcenter101** [comment]
@IgoresVer We'd be happy to look into this for you 
Kindly file a support ticket below 
https://forms.gle/2dzBgxwuZoBaD3ab6

**Comment by kent-white** [comment]
@IgoresVer you can do this https://petra.app/docs/sending-a-transaction

**Comment by Tam78787** [comment]
Vào 1:06, Th 5, 16 thg 2, 2023 Kent White ***@***.***> đã
viết:
