### ISSUE TITLE
[Bug] Derivation path does not allow manual input of derivation index

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/petra-wallet#44]
As per the screenshot, the derivation index can be rendered for clicking an account, but trying to input one manually fails

If trying to link a wallet with a high derivation path, the app first needs to load all the prior ones and takes prohibitively long

<img width="434" alt="Screenshot 2024-10-31 at 15 57 58" src="https://github.com/user-attachments/assets/d850e513-9aa4-487e-9bd5-183829787199">

**Comment by bv-aptos** [comment]
Fix has shipped with 1.2.71 extension.

Please report back with issues or suggestions for improved UX!
