### ISSUE TITLE
Generation of addresses from private keys

### ISSUE THREAD

**Issue by PROrector** [aptos-labs/petra-wallet#5]
I see a very unpleasant problem.
When importing the ETH private key into the Petra wallet, I get a completely different address in it.
What do you need to do to get access to an address similar to the ETH blockchain using the available private key?

**Comment by kent-white** [comment]
@PROrector chains have separate derivations based on various circumstances. There is no guarantee that you can use the same address across chains that use different formats.

**Comment by PROrector** [comment]
I already understood this perfectly when iancoleman utility could not decompose the mnemonic how it works with all BIP39 phrases. I assume that the point is not in derivations based, but in native applications that generate wallet addresses in their own way, and not according to the rules.

**Comment by Tam78787** [comment]
Vần ok🔄

Vào 22:18, Th 5, 16 thg 2, 2023 PROrector ***@***.***> đã
viết:

**Comment by Tam78787** [comment]
Vào 22:19, Th 5, 16 thg 2, 2023 Tâm91 vlog ***@***.***> đã viết:

**Comment by kent-white** [comment]
So yes, the bip44 path is different but the other problem you will run into is that Aptos uses Ed25519 which is not the same as ethereum's elliptic curve.

This would be the same problem you run into with going between solana and ethereum.

**Comment by PROrector** [comment]
what method of getting private key from apt address identical to evm address do you recommend?
