### ISSUE TITLE
CANNOT SIGN AND SUMMIT TRANSACTION WHICH TYPE module_bundle_payload

### ISSUE THREAD

**Issue by william-web3** [aptos-labs/petra-wallet#6]
Hi there,

I met a problem when trying to submit a transaction which is creating a coin on Aptos devnet using the Petra wallet extension.

**There is the code:**
`const transaction: Types.TransactionPayload_ModuleBundlePayload = {
        type: "module_bundle_payload",
        modules: [
          {
            bytecode:
              "0xa11ceb0b0500000009010006020604030a1b042504052924074d52089f01400adf01050ce40123000001010102000300000004000100000502010001040401010002070506000105070101000203040305060c0a020a0202030002060c0301080005060c0a020a02020101060c010503060c05030b637573746f6d5f636f696e0c6d616e616765645f636f696e067369676e65720a437573746f6d436f696e0a696e697469616c697a65046d696e740b64756d6d795f6669656c640a616464726573735f6f66d15fa3f056a9c8f16561a7e7b0d4d3baf878631d21f513846acf31138e2f4465000000000000000000000000000000000000000000000000000000000000000100020106010001040001070b000b010b020b03083800020101040001060a000b0011030b0138010200",
            abi: {
              address: account?.address || "",
              name: "public",
              friends: [],
              exposed_functions: [],
              structs: [],
            }
          },
        ],
<img width="851" alt="image" src="https://user-images.githubusercontent.com/108789245/218295823-d81f423a-51ed-42d3-a8ee-1519fb60057b.png">

      };
`
      `const response = await signAndSubmitTransaction(transaction);`

**For more information:**
Node 16.15.0
 "@aptos-labs/wallet-adapter-react": "^0.2.4"
   "@martianwallet/aptos-wallet-adapter": "^0.0.3"
    "petra-plugin-wallet-adapter": "^0.1.3"

Thanks for reading

**Comment by Tam78787** [comment]
Vào 13:13, CN, 12 thg 2, 2023 William Nguyen ***@***.***> đã
viết:
