### ISSUE TITLE
[BUG] Petra wallet unstable connection status when refreshing the page

### ISSUE THREAD

**Issue by jillxuu** [aptos-labs/petra-wallet#7]
### Issue
When frequently refreshing pages that use Petra wallet connections, people noticing that wallet connection prompt is triggered from time to time. When prompt is triggered, `await window.petra.isConnected()` in the react inspector console will return `false`. 

### Issue Impact
This issue has affected ANS, Explorer, and Wallet Adapter, which use Petra as one of the wallet connection providers.

https://user-images.githubusercontent.com/121921928/221096986-b2265bd2-7e9d-4c68-8347-20ce984e9751.mov

https://user-images.githubusercontent.com/121921928/221097010-051c88b6-9d2e-4d93-8f0e-ec3793c91478.mov

**Comment by 0xmaayan** [comment]
also, 
1. it doesn't happen on https://governance.aptosfoundation.org/ where we use only Petra
2. it doesn't happen on local env (localhost) when using the adapter - local react and nextjs apps

**Comment by Tam78787** [comment]
150 ATP

Vào 12:29, Th 6, 24 thg 2, 2023 Maayan ***@***.***> đã viết:

**Comment by hariria** [comment]
I think this is resolved @0xmaayan @jillxuu @kent-white ? Can I close?

**Comment by kent-white** [comment]
yes resolved
