### ISSUE TITLE
Transferring LP Tokens 

### ISSUE THREAD

**Issue by roadrash311** [aptos-labs/petra-wallet#8]
Was asked Petra team member on Discord to post my issue here.

Unable to transfer LP tokens between wallets.  The LP token is registered on both wallet addresses.  It is the Pancake-Cake-APT-LP.

It says not implemented when you mouse over the preview.

**Comment by hariria** [comment]
Hi, in the past you would need to ensure the LP token is registered on the wallet address you're sending to, which you alluded to above. There are often many duplicate coins so be sure that the coin info (coin address, struct tag, etc.) are accurate.

As of Petra Extension v1.2.1, however, registering is no longer necessary to transfer coins and coins should auto-register + transfer, please try it now and see if it works, let us know if you have any issues
